server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://116.6.239.133:1433;DatabaseName=WinFramework
    username: Tecx
    password: 2020
mybatis-plus:
  type-aliases-package: com.winframework.entity
  mapper-locations: classpath:mapper/*.xml
